api:
  image: abprk/flask-apache:latest
  ports:
    - "81:80"
    - "8027:22"
  volumes:
    - ../docroot/api:/var/www/html/
    - ./logs/apache2:/var/log/apache2/
  environment:
    - AUTHORIZED_KEYS="**NONE**"
  links:
    - webapp
    - db
webapp:
  image: abprk/reactjs-apache:latest
  ports:
    - "82:80"
    - "8028:22"
  volumes:
    - ../docroot/webapp:/var/www/html/
    - ./logs/apache2:/var/log/apache2/
  environment:
    - AUTHORIZED_KEYS="**NONE**"
db:
  image: mysql:5.6
  entrypoint:
    - /localdb-run.sh
  environment:
    - MYSQL_ROOT_PASSWORD=admin
  volumes:
    - ./database:/var/lib/mysql/
    - ./configuration/dev/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    - ./logs/mysql:/var/log/mysql/
    - ./configuration/dev/mysql/localdb-run.sh:/localdb-run.sh
